
spring:
  h2:
    console:
      enabled: false  # H2 웹 콘솔을 사용하겠다는 의미

datasource3:
  - name: datasourceOne
    order: 1
    data-source:
      jdbcUrl: jdbc:h2:file:d:/test_db;AUTO_SERVER=TRUE
      username: test
      password: test
      driverClassName: org.h2.Driver
      maximumPoolSize: 20